### ISSUE TITLE
Individual modules not working

### ISSUE THREAD

**Issue by Mariewelt** [connorcoley/ASKCOS#6]
Hey, I'm trying to run some individual modules like `makeit/retrosynthetic/mcts/tree_builder.py` inside docker container, but the script fails with the following error: 

```
Using Theano backend.
Traceback (most recent call last):
  File "makeit/retrosynthetic/mcts/tree_builder.py", line 1, in <module>
    from makeit.retrosynthetic.transformer import RetroTransformer
  File "/home/askcos/ASKCOS/makeit/retrosynthetic/transformer.py", line 25, in <module>
    from makeit.synthetic.evaluation.fast_filter import FastFilterScorer
  File "/home/askcos/ASKCOS/makeit/synthetic/evaluation/fast_filter.py", line 1, in <module>
    from makeit.utilities.fastfilter_utilities import Highway_self, pos_ct, true_pos, real_pos, set_keras_backend
  File "/home/askcos/ASKCOS/makeit/utilities/fastfilter_utilities.py", line 12, in <module>
    from keras.layers import merge, activations
ImportError: cannot import name activations
```
Looks like the wrong version of keras is installed inside a docker image. Do you have any ideas of how to fix this?

Thanks,
Maria

**Comment by connorcoley** [comment]
Ah, looks like there is a new version of keras that breaks that code.
Modifying requirements.txt to specify ```keras==2.2.4`` should fix the
issue. Thanks for pointing this out!

**Comment by Mariewelt** [comment]
Thanks! That helped with keras, but the script is still not working. I'm getting the following error now:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "makeit/retrosynthetic/mcts/tree_builder.py", line 489, in work
    self._target(*self._args, **self._kwargs)
  File "makeit/retrosynthetic/mcts/tree_builder.py", line 489, in work
    self.idle[i] = True
    kind, result = conn.recv()
  File "<string>", line 2, in __setitem__
    self.run()
    self.idle[i] = True
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
IOError: [Errno 104] Connection reset by peer
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    self._target(*self._args, **self._kwargs)
  File "makeit/retrosynthetic/mcts/tree_builder.py", line 489, in work
    self.idle[i] = True
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
IOError: [Errno 104] Connection reset by peer
```

I looked into file `"makeit/retrosynthetic/mcts/tree_builder.py", line 489` and uncommented line `time.sleep(0.01)`. This didn't help. However, changing the wait time to one second gave me a different error:
```

Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "makeit/retrosynthetic/mcts/tree_builder.py", line 490, in work
    self.idle[i] = True
  File "<string>", line 2, in setitem
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
IOError: [Errno 104] Connection reset by peer
Process Process-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "makeit/retrosynthetic/mcts/tree_builder.py", line 490, in work
    self.idle[i] = True
  File "<string>", line 2, in setitem
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "makeit/retrosynthetic/mcts/tree_builder.py", line 490, in work
    self.idle[i] = True
  File "<string>", line 2, in setitem
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
Process Process-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "makeit/retrosynthetic/mcts/tree_builder.py", line 490, in work
    self.idle[i] = True
  File "<string>", line 2, in setitem
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 758, in _callmethod
    conn.send((self._id, methodname, args, kwds))
IOError: [Errno 32] Broken pipe
```

**Comment by mefortunato** [comment]
Hi,

I can confirm there are some weird error messages when you run `makeit/retrosynthetic/mcts/tree_builder.py` using multiprocessing inside the docker container, but it looks like the results are returned first. The error messages look like they might be related to processes cleaning up after the tree search has completed.

I would recommend using the full application stack and spinning up the celery workers, as this cuts down on initialization time; you only have to do it once and then the workers are available for multiple tree searches. If you follow all of the instructions in the README through to the `docker-compose up -d` command, you can enter the running application service with `docker-compose exec app bash` followed by `python /usr/local/ASKCOS/makeit/retrosynthetic/mcts/tree_builder.py`. Note: you'll still have to wait for the celery workers to initialize the first time you spin up the application. You can check on their status on the web application that starts up.

Hope this helps, and let us know if there are any further questions!

**Comment by mefortunato** [comment]
Whoops, sorry, you also should add `--celery True` to the `tree_builder.py` script. So you should run:

```
python /usr/local/ASKCOS/makeit/retrosynthetic/mcts/tree_builder.py --celery True
```

inside the "app" service from the docker-compose stack.

**Comment by Mariewelt** [comment]
Thanks for your response. I'm playing around with this and let you know if I'm able to make it work. Meanwhile, I found another version of `tree_builder.py` in `makeit/retrosynthetic/` which works fine with no errors. So, I wonder what is the difference between this script and the one in `makeit/retrosynthetic/mcts`?

**Comment by connorcoley** [comment]
That ```tree_builder.py``` (in the parent ```retrosynthetic``` folder) is a depth-first search that uses a molecule-level heuristic function to steer the search toward buyable starting materials. This works fine with generous expansion times or limited search depths (maybe up to 4 reaction steps) but doesn't work as well for longer pathways. The one in the ```mcts``` folder uses upper confidence bound tree search method similar to [Marwin Segler's work](https://www.nature.com/articles/nature25978) that is instead driven by a learned template application policy.
